module System.Terminal.Encoder where

import           Data.Text (Text, pack)

import           System.Terminal.Terminal
import           System.Terminal.MonadPrinter

ansiEncode :: Command -> Text
ansiEncode = \case
    PutText t                                         -> t
    SetAnnotation Bold                                -> "\ESC[1m"
    SetAnnotation Italic                              -> ""
    SetAnnotation Underlined                          -> "\ESC[4m"
    SetAnnotation Inverted                            -> "\ESC[7m"
    SetAnnotation (Foreground (Color Dull   Black  )) -> "\ESC[30m"
    SetAnnotation (Foreground (Color Dull   Red    )) -> "\ESC[31m"
    SetAnnotation (Foreground (Color Dull   Green  )) -> "\ESC[32m"
    SetAnnotation (Foreground (Color Dull   Yellow )) -> "\ESC[33m"
    SetAnnotation (Foreground (Color Dull   Blue   )) -> "\ESC[34m"
    SetAnnotation (Foreground (Color Dull   Magenta)) -> "\ESC[35m"
    SetAnnotation (Foreground (Color Dull   Cyan   )) -> "\ESC[36m"
    SetAnnotation (Foreground (Color Dull   White  )) -> "\ESC[37m"
    SetAnnotation (Foreground (Color Bright Black  )) -> "\ESC[90m"
    SetAnnotation (Foreground (Color Bright Red    )) -> "\ESC[91m"
    SetAnnotation (Foreground (Color Bright Green  )) -> "\ESC[92m"
    SetAnnotation (Foreground (Color Bright Yellow )) -> "\ESC[93m"
    SetAnnotation (Foreground (Color Bright Blue   )) -> "\ESC[94m"
    SetAnnotation (Foreground (Color Bright Magenta)) -> "\ESC[95m"
    SetAnnotation (Foreground (Color Bright Cyan   )) -> "\ESC[96m"
    SetAnnotation (Foreground (Color Bright White  )) -> "\ESC[97m"
    SetAnnotation (Background (Color Dull   Black  )) -> "\ESC[40m"
    SetAnnotation (Background (Color Dull   Red    )) -> "\ESC[41m"
    SetAnnotation (Background (Color Dull   Green  )) -> "\ESC[42m"
    SetAnnotation (Background (Color Dull   Yellow )) -> "\ESC[43m"
    SetAnnotation (Background (Color Dull   Blue   )) -> "\ESC[44m"
    SetAnnotation (Background (Color Dull   Magenta)) -> "\ESC[45m"
    SetAnnotation (Background (Color Dull   Cyan   )) -> "\ESC[46m"
    SetAnnotation (Background (Color Dull   White  )) -> "\ESC[47m"
    SetAnnotation (Background (Color Bright Black  )) -> "\ESC[100m"
    SetAnnotation (Background (Color Bright Red    )) -> "\ESC[101m"
    SetAnnotation (Background (Color Bright Green  )) -> "\ESC[102m"
    SetAnnotation (Background (Color Bright Yellow )) -> "\ESC[103m"
    SetAnnotation (Background (Color Bright Blue   )) -> "\ESC[104m"
    SetAnnotation (Background (Color Bright Magenta)) -> "\ESC[105m"
    SetAnnotation (Background (Color Bright Cyan   )) -> "\ESC[106m"
    SetAnnotation (Background (Color Bright White  )) -> "\ESC[107m"
    ResetAnnotation Bold                              -> "\ESC[22m"
    ResetAnnotation Italic                            -> ""
    ResetAnnotation Underlined                        -> "\ESC[24m"
    ResetAnnotation Inverted                          -> "\ESC[27m"
    ResetAnnotation (Foreground _)                    -> "\ESC[39m"
    ResetAnnotation (Background _)                    -> "\ESC[49m"
    ResetAnnotations                                  -> "\ESC[m"
    MoveCursorUp i                                    -> "\ESC[" <> pack (show i) <> "A"
    MoveCursorDown i                                  -> "\ESC[" <> pack (show i) <> "B"
    MoveCursorLeft i                                  -> "\ESC[" <> pack (show i) <> "D"
    MoveCursorRight i                                 -> "\ESC[" <> pack (show i) <> "C"
    SetCursorPosition (x,y)                           -> "\ESC[" <> pack (show $ x + 1) <> ";" <> pack (show $ y + 1) <> "H"
    SetCursorPositionVertical i                       -> "\ESC[" <> pack (show $ i + 1) <> "d"
    SetCursorPositionHorizontal i                     -> "\ESC[" <> pack (show $ i + 1) <> "G"
    SaveCursorPosition                                -> "\ESC7"
    RestoreCursorPosition                             -> "\ESC8"
    ShowCursor                                        -> "\ESC[?25h"
    HideCursor                                        -> "\ESC[?25l"
    ClearLine                                         -> "\ESC[2K"
    ClearLineLeft                                     -> "\ESC[1K"
    ClearLineRight                                    -> "\ESC[0K"
    ClearScreen                                       -> "\ESC[2J"
    ClearScreenAbove                                  -> "\ESC[1J"
    ClearScreenBelow                                  -> "\ESC[0J"
    UseAlternateScreenBuffer   True                   -> "\ESC[?1049h"
    UseAlternateScreenBuffer  False                   -> "\ESC[?1049l"